apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tilda-atmos-data
  namespace: ventureforum
  labels:
    app: tilda-atmos
    project: ventureforum
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
