apiVersion: v1
kind: Secret
metadata:
  name: atmos-credentials
  namespace: ventureforum
  labels:
    project: ventureforum
type: Opaque
stringData:
  ATMOS_CONSUMER_KEY: "***REMOVED***"
  ATMOS_CONSUMER_SECRET: "***REMOVED***"
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-jscorp
  namespace: ventureforum
  labels:
    project: ventureforum
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.jscorp.uz": {
          "username": "***REMOVED***",
          "password": "***REMOVED***",
          "auth": "anNjb3JwdGVjaDoyMzA5MjAwNQ=="
        }
      }
    }
