apiVersion: v1
kind: Secret
metadata:
  name: atmos-credentials
  labels:
    project: ventureforum
type: Opaque
stringData:
  ATMOS_CONSUMER_KEY: "***REMOVED***"
  ATMOS_CONSUMER_SECRET: "***REMOVED***"
