apiVersion: v1
kind: Secret
metadata:
  name: atmos-credentials
  namespace: ventureforum
  labels:
    project: ventureforum
type: Opaque
stringData:
  ATMOS_CONSUMER_KEY: "lu6ZA2sKhytuCuvkzSVG2kOurP0a"
  ATMOS_CONSUMER_SECRET: "iBKm7aXVsDG9lHvW0tHI3mTMDWsa"
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-jscorp
  namespace: ventureforum
  labels:
    project: ventureforum
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.jscorp.uz": {
          "username": "jscorptech",
          "password": "23092005",
          "auth": "anNjb3JwdGVjaDoyMzA5MjAwNQ=="
        }
      }
    }
