apiVersion: v1
kind: Secret
metadata:
  name: atmos-credentials
  namespace: mostinvest
  labels:
    project: mostinvest
type: Opaque
data:
  ATMOS_CONSUMER_KEY: bHU2WkEyc0toeXR1Q3V2a3pTVkcya091clAwYQ==
  ATMOS_CONSUMER_SECRET: aUJLbTdhWFZzREc5bEh2VzB0SEkzbVRNRFdzYQ==
